/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import DAOs.teacherDAO;
import entities.teacher;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import utils.browseImage;
import utils.imageConversion;

/**
 *
 * @author hp
 */
public class addTeacher extends javax.swing.JPanel {
    teacherDAO dao=new teacherDAO();
    imageConversion ic = new imageConversion();

    /**
     * Creates new form updateStudent
     */
    public addTeacher() {
        initComponents();
    }

    public void resetValues(){
        id.setText(String.valueOf(dao.getMaxId()));
        name.setText("");
        BPS.setText("");
        education.setText("");
        address.setText("");
        orderNo.setText("");
        cast.setText("");
        spouceName.setText("");
        email.setText("");
        spouceCNIC.setText("");
        religion.setText("");
        cnic.setText("");
        phone.setText("");
        path.setText("");
        personalNo.setText("");
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageicon.png"))); 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addstd = new javax.swing.JPanel();
        education = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        brows = new javax.swing.JButton();
        birth = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        orderNo = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        BPS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        spouceName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        religion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cast = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spouceCNIC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        personalNo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        registration = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        joining = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        regular = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        add = new javax.swing.JButton();

        setLayout(null);

        addstd.setLayout(null);

        education.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        education.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                educationKeyPressed(evt);
            }
        });
        addstd.add(education);
        education.setBounds(270, 170, 270, 34);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Education");
        addstd.add(jLabel3);
        jLabel3.setBounds(160, 170, 120, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        addstd.add(jLabel4);
        jLabel4.setBounds(160, 70, 120, 30);

        name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        addstd.add(name);
        name.setBounds(270, 70, 270, 34);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Sr. NO");
        addstd.add(jLabel5);
        jLabel5.setBounds(160, 20, 120, 30);

        id.setEditable(false);
        id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addstd.add(id);
        id.setBounds(270, 20, 270, 34);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        addstd.add(jLabel6);
        jLabel6.setBounds(160, 420, 120, 30);

        address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        addstd.add(address);
        address.setBounds(270, 420, 680, 34);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("BPS");
        addstd.add(jLabel7);
        jLabel7.setBounds(160, 120, 120, 30);

        path.setEditable(false);
        path.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addstd.add(path);
        path.setBounds(1020, 350, 190, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Date of Birth");
        addstd.add(jLabel8);
        jLabel8.setBounds(580, 220, 120, 30);

        brows.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        brows.setText("Browse");
        brows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsActionPerformed(evt);
            }
        });
        addstd.add(brows);
        brows.setBounds(1020, 400, 190, 30);

        birth.setDateFormatString("yyyy-MM-dd");
        addstd.add(birth);
        birth.setBounds(700, 220, 250, 30);
        birth.setDate(Date.valueOf(LocalDate.now()));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Order No.");
        addstd.add(jLabel9);
        jLabel9.setBounds(580, 70, 120, 30);

        orderNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orderNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                orderNoKeyPressed(evt);
            }
        });
        addstd.add(orderNo);
        orderNo.setBounds(700, 70, 250, 34);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageicon.png"))); // NOI18N
        addstd.add(image);
        image.setBounds(1030, 200, 140, 130);

        BPS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addstd.add(BPS);
        BPS.setBounds(270, 120, 270, 34);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Email Address");
        addstd.add(jLabel11);
        jLabel11.setBounds(580, 120, 120, 30);

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addstd.add(email);
        email.setBounds(700, 120, 250, 34);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Spouse Name");
        addstd.add(jLabel12);
        jLabel12.setBounds(160, 370, 120, 30);

        spouceName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spouceName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spouceNameKeyPressed(evt);
            }
        });
        addstd.add(spouceName);
        spouceName.setBounds(270, 370, 270, 34);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Religion");
        addstd.add(jLabel15);
        jLabel15.setBounds(160, 320, 120, 30);

        religion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addstd.add(religion);
        religion.setBounds(270, 320, 270, 34);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Cast");
        addstd.add(jLabel16);
        jLabel16.setBounds(590, 320, 120, 30);

        cast.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addstd.add(cast);
        cast.setBounds(700, 320, 250, 34);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Spouse CNIC");
        addstd.add(jLabel17);
        jLabel17.setBounds(580, 370, 120, 30);

        spouceCNIC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spouceCNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spouceCNICKeyPressed(evt);
            }
        });
        addstd.add(spouceCNIC);
        spouceCNIC.setBounds(700, 370, 250, 34);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Personal No.");
        addstd.add(jLabel10);
        jLabel10.setBounds(580, 20, 120, 30);

        personalNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        personalNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                personalNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                personalNoKeyReleased(evt);
            }
        });
        addstd.add(personalNo);
        personalNo.setBounds(700, 20, 250, 34);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Registration Date");
        addstd.add(jLabel18);
        jLabel18.setBounds(980, 20, 120, 30);

        registration.setDateFormatString("yyyy-MM-dd");
        addstd.add(registration);
        registration.setBounds(980, 50, 250, 30);
        registration.setDate(Date.valueOf(LocalDate.now()));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Phone No");
        addstd.add(jLabel19);
        jLabel19.setBounds(580, 170, 120, 30);

        phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        addstd.add(phone);
        phone.setBounds(700, 170, 250, 34);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Joining Date");
        addstd.add(jLabel21);
        jLabel21.setBounds(160, 270, 120, 30);

        joining.setDateFormatString("yyyy-MM-dd");
        addstd.add(joining);
        joining.setBounds(270, 270, 270, 30);
        joining.setDate(Date.valueOf(LocalDate.now()));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Date of Regular");
        addstd.add(jLabel22);
        jLabel22.setBounds(580, 270, 120, 30);

        regular.setDateFormatString("yyyy-MM-dd");
        addstd.add(regular);
        regular.setBounds(700, 270, 250, 30);
        regular.setDate(Date.valueOf(LocalDate.now()));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("CNIC");
        addstd.add(jLabel23);
        jLabel23.setBounds(160, 220, 120, 30);

        cnic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnicKeyPressed(evt);
            }
        });
        addstd.add(cnic);
        cnic.setBounds(270, 220, 270, 34);

        add.setBackground(new java.awt.Color(0, 153, 0));
        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setText("Add Teacher");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        addstd.add(add);
        add.setBounds(440, 470, 210, 40);

        add(addstd);
        addstd.setBounds(0, 0, 1280, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void educationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_educationKeyPressed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_educationKeyPressed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void spouceNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spouceNameKeyPressed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_spouceNameKeyPressed

    private void spouceCNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spouceCNICKeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            spouceCNIC.setEditable(true);
        }else{
            spouceCNIC.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_spouceCNICKeyPressed

    private void browsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsActionPerformed
        browseImage browse = new browseImage();
        browse.brows(image, path);
        // TODO add your handling code here:
    }//GEN-LAST:event_browsActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void personalNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personalNoKeyReleased
        
// TODO add your handling code here:
    }//GEN-LAST:event_personalNoKeyReleased

    private void cnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicKeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            cnic.setEditable(true);
        }else{
            cnic.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicKeyPressed

    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        teacher teach = new teacher();
        teach.setId(Integer.parseInt(id.getText()));
        teach.setName(name.getText());
        teach.setPersonalNo(Integer.parseInt(personalNo.getText()));
        teach.setOrderNo(Integer.parseInt(orderNo.getText()));
        teach.setBPS(BPS.getText());
        teach.setAddress(address.getText());
        teach.setDOB(birth.getDate());
        teach.setDOJ(joining.getDate());
        teach.setDOR(registration.getDate());
        teach.setCreated(registration.getDate());
        teach.setCNIC(cnic.getText());
        teach.setPh(phone.getText());
        teach.setEducation(education.getText());
        teach.setEmailAddress(email.getText());
        teach.setDeleted(false);
        teach.setSpouceName(spouceName.getText());
        teach.setSpouceCNIC(spouceCNIC.getText());
        teach.setCast(cast.getText());
        teach.setReligion(religion.getText());
        teach.setImage(ic.fileToByte(path.getText()));
        dao.saveTeacher(teach);
        JOptionPane.showMessageDialog(null, "Teach Saved to Staff successfully...");
        resetValues();
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void orderNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderNoKeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            orderNo.setEditable(true);
        }else{
            orderNo.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNoKeyPressed

    private void personalNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personalNoKeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            personalNo.setEditable(true);
        }else{
            personalNo.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_personalNoKeyPressed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
            phone.setEditable(true);
        }else{
            phone.setEditable(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPS;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JPanel addstd;
    private com.toedter.calendar.JDateChooser birth;
    private javax.swing.JButton brows;
    private javax.swing.JTextField cast;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField education;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser joining;
    private javax.swing.JTextField name;
    private javax.swing.JTextField orderNo;
    private javax.swing.JTextField path;
    private javax.swing.JTextField personalNo;
    private javax.swing.JTextField phone;
    private com.toedter.calendar.JDateChooser registration;
    private com.toedter.calendar.JDateChooser regular;
    private javax.swing.JTextField religion;
    private javax.swing.JTextField spouceCNIC;
    private javax.swing.JTextField spouceName;
    // End of variables declaration//GEN-END:variables
}

