/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import DAOs.studentDAO;
import java.sql.Date;
import utils.browseImage;
import java.time.LocalDate;

/**
 *
 * @author Laptop Point
 */
public class Home extends javax.swing.JFrame {
     studentDAO dao=new studentDAO();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        id.setText(String.valueOf(dao.getMaxId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        StudentBox = new javax.swing.JComboBox<>();
        TeacherBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cnic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        admission = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        className = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        roll1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        roll2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        name3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        roll3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        roll4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setForeground(new java.awt.Color(0.0f, 0.0f, 0.0f, 0.1f));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 20, 1360, 80);

        StudentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Details", "View Students", "Add Student", "Update Student", "Delete Student" }));
        StudentBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                StudentBoxItemStateChanged(evt);
            }
        });

        TeacherBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher Details", "View Teachers", "Add  Teacher", "Update Teacher", "Delete Teacher" }));
        TeacherBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TeacherBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(StudentBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeacherBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1064, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentBox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(TeacherBox)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 100, 1370, 30);

        jPanel4.setLayout(null);

        cnic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(cnic);
        cnic.setBounds(270, 200, 205, 34);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("B.Form No");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(160, 200, 120, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(160, 150, 120, 30);

        name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(name);
        name.setBounds(270, 150, 205, 34);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Sr. NO");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(160, 100, 120, 30);

        id.setEditable(false);
        id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(id);
        id.setBounds(270, 100, 205, 34);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(160, 400, 120, 30);

        address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel4.add(address);
        address.setBounds(270, 400, 560, 34);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Class Name");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(510, 100, 120, 30);

        path.setEditable(false);
        path.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(path);
        path.setBounds(880, 370, 140, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Admission Date");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(850, 110, 120, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(380, 20, 390, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(880, 410, 140, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Add Student");
        jPanel4.add(jButton2);
        jButton2.setBounds(430, 470, 240, 40);

        admission.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(admission);
        admission.setBounds(850, 150, 180, 30);
        admission.setDate(Date.valueOf(LocalDate.now()));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Roll No");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(510, 150, 120, 30);

        roll.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(roll);
        roll.setBounds(620, 150, 205, 34);

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageicon.png"))); // NOI18N
        jPanel4.add(image);
        image.setBounds(880, 220, 140, 130);

        className.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(className);
        className.setBounds(620, 100, 205, 34);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Father's Name");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(510, 200, 120, 30);

        name1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(name1);
        name1.setBounds(620, 200, 205, 34);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Father's CNIC");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(160, 250, 120, 30);

        roll1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(roll1);
        roll1.setBounds(270, 250, 205, 34);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Mother's Name");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(160, 300, 120, 30);

        name2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(name2);
        name2.setBounds(270, 300, 205, 34);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Mother's CNIC");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(510, 300, 120, 30);

        roll2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(roll2);
        roll2.setBounds(620, 300, 205, 34);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Religion");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(160, 350, 120, 30);

        name3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(name3);
        name3.setBounds(270, 350, 205, 34);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Cast");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(510, 350, 120, 30);

        roll3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(roll3);
        roll3.setBounds(620, 350, 205, 34);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Father's Ph.");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(510, 250, 120, 30);

        roll4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(roll4);
        roll4.setBounds(620, 250, 205, 34);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(140, 150, 1050, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/homeback.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1570, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_StudentBoxItemStateChanged
        TeacherBox.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentBoxItemStateChanged

    private void TeacherBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TeacherBoxItemStateChanged
        StudentBox.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherBoxItemStateChanged

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        browseImage browse = new browseImage();
        browse.brows(image, path);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> StudentBox;
    private javax.swing.JComboBox<String> TeacherBox;
    private javax.swing.JTextField address;
    private com.toedter.calendar.JDateChooser admission;
    private javax.swing.JTextField className;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField id;
    public javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JTextField path;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField roll1;
    private javax.swing.JTextField roll2;
    private javax.swing.JTextField roll3;
    private javax.swing.JTextField roll4;
    // End of variables declaration//GEN-END:variables
}
