/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import DAOs.studentDAO;
import entities.fileUpdater;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import utils.BrowsingUtil;
import utils.fileOperations;

/**
 *
 * @author hp
 */
public class settings extends javax.swing.JPanel {
    fileOperations op = new fileOperations();
    /**
     * Creates new form viewStudent
     */
    public settings() {
        initComponents();
        
    }
    
    public void setValues(){
        details.setVisible(false);
        name.setText("");
        jPasswordField1.setText("");
        dbFile.setText(Login.url);
        newUser.setText(Login.userName);
        newPass1.setText(Login.password);
        newPass2.setText(Login.password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        details = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        newUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        newPass2 = new javax.swing.JPasswordField();
        newPass1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        dbFile = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1280, 300));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("User Name");
        add(jLabel1);
        jLabel1.setBounds(110, 70, 150, 30);

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        add(name);
        name.setBounds(250, 70, 220, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(570, 70, 150, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Verify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(960, 70, 130, 30);

        details.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("New Password");
        details.add(jLabel4);
        jLabel4.setBounds(110, 130, 150, 30);

        newUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newUserKeyReleased(evt);
            }
        });
        details.add(newUser);
        newUser.setBounds(250, 70, 220, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("New User Name");
        details.add(jLabel3);
        jLabel3.setBounds(110, 70, 150, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        details.add(jLabel5);
        jLabel5.setBounds(520, 130, 150, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Update File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        details.add(jButton2);
        jButton2.setBounds(570, 270, 190, 30);

        newPass2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        details.add(newPass2);
        newPass2.setBounds(650, 130, 220, 30);

        newPass1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        details.add(newPass1);
        newPass1.setBounds(250, 130, 220, 30);
        details.add(jSeparator1);
        jSeparator1.setBounds(110, 190, 760, 10);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Datebase File");
        details.add(jLabel6);
        jLabel6.setBounds(110, 230, 150, 30);

        dbFile.setEditable(false);
        dbFile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dbFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dbFileKeyReleased(evt);
            }
        });
        details.add(dbFile);
        dbFile.setBounds(250, 230, 620, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("Update Username and Pasword");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        details.add(jButton3);
        jButton3.setBounds(550, 70, 240, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("Browse File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        details.add(jButton4);
        jButton4.setBounds(370, 270, 160, 30);

        add(details);
        details.setBounds(110, 130, 980, 330);
        details.setVisible(false);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        add(jPasswordField1);
        jPasswordField1.setBounds(660, 70, 220, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void newUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(dbFile.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No database file selected...", "DB file updation error..", JOptionPane.ERROR_MESSAGE);
        }else{
            List<fileUpdater> updaters=new ArrayList<>();
            fileUpdater updater = new fileUpdater();
            updater.setCurrentString("DataBaseFile:@%&%&@:");
            updater.setUpdatedString(updater.getCurrentString()+dbFile.getText());
            op.updateFile(Login.credURL, updaters);
            JOptionPane.showMessageDialog(null, "Database file updated Succesfulle...");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dbFileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbFileKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dbFileKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(newPass1.getText().equals(newPass2.getText()) && !newPass1.getText().isEmpty() && !newUser.getText().isEmpty())
        {
            fileUpdater updateUser = new fileUpdater();
            updateUser.setCurrentString("Username:@%&%&@:");
            updateUser.setUpdatedString(updateUser.getCurrentString()+newUser.getText());
            fileUpdater updatePass = new fileUpdater();
            updatePass.setCurrentString("Password:@%&%&@:");
            updatePass.setUpdatedString(updatePass.getCurrentString()+newPass1.getText());
            List<fileUpdater> updaters = new ArrayList<>();
            updaters.add(updateUser);
            updaters.add(updatePass);
            op.updateFile(Login.credURL, updaters);
            JOptionPane.showMessageDialog(null, "Username and password updated successfully");
        }else{
            JOptionPane.showMessageDialog(null, "Invalid input Error", "Please recheck new username and passwords...",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dbFile.setText(BrowsingUtil.browseFile());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(name.getText().equals(Login.userName) && jPasswordField1.getText().equals(Login.password))
        {
            details.setVisible(true);
        }else{
            details.setVisible(false);
            JOptionPane.showMessageDialog(null, "Autherntication Error", "Invalid Username or Password",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dbFile;
    private javax.swing.JPanel details;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField newPass1;
    private javax.swing.JPasswordField newPass2;
    private javax.swing.JTextField newUser;
    // End of variables declaration//GEN-END:variables
}
