/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import DAOs.studentDAO;
import entities.student;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.popups;

/**
 *
 * @author hp
 */
public class viewStudent extends javax.swing.JPanel {
    studentDAO stDAO = new studentDAO();
    /**
     * Creates new form viewStudent
     */
    public viewStudent() {
        initComponents();
        
    }
    
    public void setValues(){
        List<student> students = stDAO.findAll();
        setTable(jTable1, students);
    }

    public void setTable(JTable table, List<student> students){
        DefaultTableModel dtm=(DefaultTableModel) table.getModel();
        int rows=dtm.getRowCount();
        for(int i=0; i<rows; i++){
            dtm.removeRow(0);
        }
        for(student std:students){
            String data[]={
                std.getRollNo(),
                std.getName(),
                std.getClassName(),
                std.getCNIC(),
                std.getReligion(),
                std.getCast(),
                std.getFatherName(),
                std.getFatherPh(),
                std.getMotherName(),
                String.valueOf(std.getAdmissionDate())
            };
            dtm.addRow(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        namePopup = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 300));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Student Name");
        add(jLabel1);
        jLabel1.setBounds(30, 20, 150, 30);

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        add(name);
        name.setBounds(170, 20, 220, 30);

        nameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(nameList);

        javax.swing.GroupLayout namePopupLayout = new javax.swing.GroupLayout(namePopup);
        namePopup.setLayout(namePopupLayout);
        namePopupLayout.setHorizontalGroup(
            namePopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        namePopupLayout.setVerticalGroup(
            namePopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        add(namePopup);
        namePopup.setBounds(170, 50, 220, 110);
        namePopup.setVisible(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Roll No", "Name", "Class", "B.Form", "Religion", "Cast", "Father Name", "Father Ph", "Mother Name", "Admission"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 1280, 450);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(450, 20, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        popups pop=new popups();
        pop.setStudentNamePopup(name.getText(), nameList, namePopup);
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void nameListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameListMouseClicked
        name.setText(nameList.getSelectedValue());
        namePopup.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_nameListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<student> stList=stDAO.getNameByAlpha(name.getText());
        setTable(jTable1, stList);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JList<String> nameList;
    private javax.swing.JPanel namePopup;
    // End of variables declaration//GEN-END:variables
}
